version: "3.9"

services:

  mongo1:
    image: mongo:8.0
    container_name: mongo1
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"

  mongo2:
    image: mongo:8.0
    container_name: mongo2
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"

  mongo3:
    image: mongo:8.0
    container_name: mongo3
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27019:27017"

  app:
    build:
      context: ./app
    container_name: change-stream-app

    depends_on:
      - mongo1
      - mongo2
      - mongo3

    env_file:
      - ./app/.env

    volumes:
      - ./app:/app